//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.18 at 11:38:35 AM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.12", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iso.std.iso._20022.tech.xsd.pacs_008_001;
